spring:
  datasource:
    username: C##Rent
    password: tiger
    url: "jdbc:oracle:thin:@localhost:1521:orcl"
  jpa:
    database-platform: org.hibernate.dialect.Oracle8iDialect
    hibernate:
      ddl-auto: update
